import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Layout } from '@/components/layout/Layout';
import { 
  LayoutDashboard, Trophy, Users, BookOpen, TrendingUp, 
  Plus, ArrowRight, Download, Filter, Award, Target
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { StatCard } from '@/components/ui/stat-card';
import { AnimatedCard, AnimatedList, AnimatedListItem } from '@/components/ui/animated-container';
import { ChallengesManagement } from '@/components/dashboard/ChallengesManagement';
import { useAuth } from '@/contexts/AuthContext';
import { supabase } from '@/integrations/supabase/client';
import { generatePDF } from '@/lib/pdf-export';
import { motion } from 'framer-motion';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';

const TeacherDashboard = () => {
  const { user, profile, isTeacher, isLibrarian } = useAuth();
  const navigate = useNavigate();
  const [activeTab, setActiveTab] = useState('overview');
  const [stats, setStats] = useState({ challenges: 0, participants: 0, booksRead: 0, topClass: '-' });
  const [challenges, setChallenges] = useState<any[]>([]);
  const [studentProgress, setStudentProgress] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [challengeModalOpen, setChallengeModalOpen] = useState(false);
  const [editingChallenge, setEditingChallenge] = useState<any>(null);
  const [classFilter, setClassFilter] = useState('all');

  useEffect(() => {
    if (isTeacher || isLibrarian) {
      fetchDashboardData();
    }
  }, [isTeacher, isLibrarian]);

  const fetchDashboardData = async () => {
    setIsLoading(true);
    
    // Fetch challenges created by this user
    const { data: challengesData } = await supabase
      .from('challenges')
      .select('*, challenge_participants(count)')
      .eq('created_by', user?.id)
      .order('created_at', { ascending: false });

    if (challengesData) {
      setChallenges(challengesData);
      const totalParticipants = challengesData.reduce((sum, c) => sum + (c.challenge_participants?.[0]?.count || 0), 0);
      setStats(prev => ({ ...prev, challenges: challengesData.length, participants: totalParticipants }));
    }

    // Fetch student reading progress (simplified - actual would need more data)
    const { data: borrowingData } = await supabase
      .from('borrowing_records')
      .select('user_id, status, book:books(title)')
      .eq('status', 'returned')
      .limit(100);

    if (borrowingData) {
      // Group by user
      const userBooks: Record<string, number> = {};
      borrowingData.forEach(record => {
        userBooks[record.user_id] = (userBooks[record.user_id] || 0) + 1;
      });
      setStats(prev => ({ ...prev, booksRead: borrowingData.length }));
    }

    // Fetch profiles for student list
    const { data: profilesData } = await supabase
      .from('profiles')
      .select('*')
      .limit(50);

    if (profilesData) {
      setStudentProgress(profilesData);
    }

    setIsLoading(false);
  };

  const fetchChallenges = async () => {
    const { data } = await supabase
      .from('challenges')
      .select('*, challenge_participants(id, user_id, progress, completed)')
      .order('created_at', { ascending: false });
    if (data) setChallenges(data);
  };

  const exportStudentReport = () => {
    generatePDF({
      title: 'Student Reading Report',
      subtitle: `Generated by ${profile?.full_name || 'Teacher'}`,
      generatedBy: profile?.full_name || 'Teacher',
      data: studentProgress.map(s => ({
        name: s.full_name || 'Unknown',
        class: s.class_name || '-',
        house: s.house_name || '-',
      })),
      columns: [
        { header: 'Student Name', key: 'name' },
        { header: 'Class', key: 'class' },
        { header: 'House', key: 'house' },
      ],
    });
  };

  if (!user || (!isTeacher && !isLibrarian)) {
    return (
      <Layout>
        <div className="container mx-auto px-4 py-12 text-center">
          <LayoutDashboard className="h-16 w-16 mx-auto text-primary mb-4" />
          <h1 className="font-display text-2xl font-bold mb-2">Access Restricted</h1>
          <p className="text-muted-foreground mb-6">Teacher access required</p>
          <Button onClick={() => navigate('/')}>Return Home</Button>
        </div>
      </Layout>
    );
  }

  return (
    <Layout>
      <div className="container mx-auto px-4 py-8 lg:px-8">
        {/* Header */}
        <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }} className="mb-8">
          <div className="flex items-center gap-3">
            <LayoutDashboard className="h-8 w-8 text-primary" />
            <h1 className="font-display text-3xl font-bold">Teacher Dashboard</h1>
          </div>
          <p className="text-muted-foreground mt-1">Manage challenges and track student progress</p>
        </motion.div>

        {/* Stats */}
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4 mb-8">
          <StatCard title="My Challenges" value={stats.challenges} icon={Trophy} iconColor="text-accent-gold" iconBg="bg-accent-gold/10" />
          <StatCard title="Participants" value={stats.participants} icon={Users} iconColor="text-primary" iconBg="bg-primary/10" />
          <StatCard title="Books Read" value={stats.booksRead} icon={BookOpen} iconColor="text-accent-green" iconBg="bg-accent-green/10" />
          <StatCard title="Top Class" value={stats.topClass} icon={TrendingUp} iconColor="text-accent-orange" iconBg="bg-accent-orange/10" />
        </div>

        {/* Tabs */}
        <Tabs value={activeTab} onValueChange={setActiveTab}>
          <TabsList className="mb-6 flex-wrap h-auto gap-1">
            <TabsTrigger value="overview">Overview</TabsTrigger>
            <TabsTrigger value="challenges">Challenges</TabsTrigger>
            <TabsTrigger value="students">Students</TabsTrigger>
            <TabsTrigger value="leaderboard">Leaderboard</TabsTrigger>
          </TabsList>

          {/* Overview */}
          <TabsContent value="overview">
            <div className="grid gap-6 lg:grid-cols-2">
              {/* Quick Actions */}
              <AnimatedCard delay={0.1} className="bg-card rounded-xl p-6 shadow-sm border">
                <h2 className="font-display text-lg font-semibold mb-4">Quick Actions</h2>
                <div className="grid gap-3 sm:grid-cols-2">
                  {[
                    { title: 'New Challenge', icon: Plus, onClick: () => { setEditingChallenge(null); setChallengeModalOpen(true); } },
                    { title: 'View Students', icon: Users, onClick: () => setActiveTab('students') },
                    { title: 'Export Report', icon: Download, onClick: exportStudentReport },
                    { title: 'Leaderboard', icon: Trophy, onClick: () => setActiveTab('leaderboard') },
                  ].map((action) => (
                    <Button
                      key={action.title}
                      variant="outline"
                      className="h-auto py-4 justify-start gap-3"
                      onClick={action.onClick}
                    >
                      <action.icon className="h-5 w-5 text-primary" />
                      {action.title}
                    </Button>
                  ))}
                </div>
              </AnimatedCard>

              {/* Recent Challenges */}
              <AnimatedCard delay={0.2} className="bg-card rounded-xl p-6 shadow-sm border">
                <div className="flex items-center justify-between mb-4">
                  <h2 className="font-display text-lg font-semibold">Active Challenges</h2>
                  <Button variant="ghost" size="sm" onClick={() => setActiveTab('challenges')}>
                    View All
                  </Button>
                </div>
                {challenges.length > 0 ? (
                  <AnimatedList className="space-y-3">
                    {challenges.slice(0, 3).map((challenge) => (
                      <AnimatedListItem key={challenge.id} className="flex items-center gap-3 p-3 rounded-lg bg-muted/50">
                        <span className="text-2xl">{challenge.badge_icon || '🏆'}</span>
                        <div className="flex-1 min-w-0">
                          <p className="font-medium truncate">{challenge.title}</p>
                          <p className="text-xs text-muted-foreground">
                            {challenge.challenge_participants?.[0]?.count || 0} participants
                          </p>
                        </div>
                        <Badge variant={challenge.status === 'active' ? 'default' : 'secondary'}>
                          {challenge.status}
                        </Badge>
                      </AnimatedListItem>
                    ))}
                  </AnimatedList>
                ) : (
                  <div className="text-center py-8 text-muted-foreground">
                    <Trophy className="h-10 w-10 mx-auto mb-2 opacity-50" />
                    <p>No challenges yet</p>
                    <Button variant="link" onClick={() => setChallengeModalOpen(true)}>
                      Create your first challenge
                    </Button>
                  </div>
                )}
              </AnimatedCard>
            </div>
          </TabsContent>

          {/* Challenges */}
          <TabsContent value="challenges">
            <ChallengesManagement showOnlyMyChallenge={true} restrictToClass={true} />
          </TabsContent>

          {/* Students */}
          <TabsContent value="students">
            <div className="flex flex-col sm:flex-row justify-between gap-4 mb-4">
              <h2 className="font-semibold">Student Progress</h2>
              <div className="flex gap-2">
                <Select value={classFilter} onValueChange={setClassFilter}>
                  <SelectTrigger className="w-[150px]">
                    <SelectValue placeholder="Filter by class" />
                  </SelectTrigger>
                  <SelectContent className="bg-popover">
                    <SelectItem value="all">All Classes</SelectItem>
                    <SelectItem value="7A">Grade 7A</SelectItem>
                    <SelectItem value="7B">Grade 7B</SelectItem>
                    <SelectItem value="8A">Grade 8A</SelectItem>
                    <SelectItem value="8B">Grade 8B</SelectItem>
                  </SelectContent>
                </Select>
                <Button variant="outline" size="sm" onClick={exportStudentReport}>
                  <Download className="h-4 w-4 mr-1" />Export
                </Button>
              </div>
            </div>
            <div className="border rounded-lg overflow-auto">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Student</TableHead>
                    <TableHead>Class</TableHead>
                    <TableHead>House</TableHead>
                    <TableHead className="text-right">Actions</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {studentProgress
                    .filter(s => classFilter === 'all' || s.class_name?.includes(classFilter))
                    .slice(0, 20)
                    .map((student) => (
                    <TableRow key={student.id}>
                      <TableCell className="font-medium">{student.full_name || 'Unknown'}</TableCell>
                      <TableCell>{student.class_name || '-'}</TableCell>
                      <TableCell>
                        <Badge variant="secondary">{student.house_name || '-'}</Badge>
                      </TableCell>
                      <TableCell className="text-right">
                        <Button variant="ghost" size="sm">View</Button>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          </TabsContent>

          {/* Leaderboard */}
          <TabsContent value="leaderboard">
            <div className="grid gap-6 lg:grid-cols-2">
              {/* Class Leaderboard */}
              <AnimatedCard delay={0.1} className="bg-card rounded-xl p-6 shadow-sm border">
                <h2 className="font-display text-lg font-semibold mb-4 flex items-center gap-2">
                  <Trophy className="h-5 w-5 text-accent-gold" />
                  Top Classes
                </h2>
                <div className="space-y-3">
                  {['Grade 8A', 'Grade 7B', 'Grade 8B', 'Grade 7A', 'Grade 9A'].map((cls, i) => (
                    <div key={cls} className="flex items-center gap-3">
                      <div className={`w-8 h-8 rounded-full flex items-center justify-center text-sm font-bold ${
                        i === 0 ? 'bg-accent-gold text-accent-gold-foreground' :
                        i === 1 ? 'bg-muted-foreground/30 text-foreground' :
                        i === 2 ? 'bg-accent-orange/30 text-accent-orange' : 'bg-muted text-muted-foreground'
                      }`}>
                        {i + 1}
                      </div>
                      <div className="flex-1">
                        <p className="font-medium">{cls}</p>
                        <Progress value={100 - i * 15} className="h-2 mt-1" />
                      </div>
                      <span className="font-semibold">{150 - i * 20}</span>
                    </div>
                  ))}
                </div>
              </AnimatedCard>

              {/* House Leaderboard */}
              <AnimatedCard delay={0.2} className="bg-card rounded-xl p-6 shadow-sm border">
                <h2 className="font-display text-lg font-semibold mb-4 flex items-center gap-2">
                  <Award className="h-5 w-5 text-primary" />
                  House Rankings
                </h2>
                <div className="space-y-3">
                  {[
                    { name: 'Phoenix', color: 'bg-destructive/20 text-destructive', books: 245 },
                    { name: 'Dragon', color: 'bg-accent-green/20 text-accent-green', books: 230 },
                    { name: 'Griffin', color: 'bg-accent-gold/20 text-accent-gold', books: 215 },
                    { name: 'Pegasus', color: 'bg-primary/20 text-primary', books: 198 },
                  ].map((house, i) => (
                    <div key={house.name} className="flex items-center gap-3 p-3 rounded-lg bg-muted/50">
                      <div className={`w-10 h-10 rounded-lg flex items-center justify-center font-bold ${house.color}`}>
                        {i + 1}
                      </div>
                      <div className="flex-1">
                        <p className="font-medium">{house.name}</p>
                        <p className="text-xs text-muted-foreground">{house.books} books read</p>
                      </div>
                      {i === 0 && <span className="text-2xl">👑</span>}
                    </div>
                  ))}
                </div>
              </AnimatedCard>
            </div>
          </TabsContent>
        </Tabs>
      </div>

      {/* Challenge Modal */}
      <ChallengeForm 
        isOpen={challengeModalOpen} 
        onClose={() => setChallengeModalOpen(false)} 
        challenge={editingChallenge}
        onSuccess={fetchChallenges} 
      />
    </Layout>
  );
};

export default TeacherDashboard;
